apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  labels:
    name: cadvisor
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: tcp-service
      targetPort: 8080
  selector:
    name: cadvisor